/* Book of the Dead World: the journey. Generated by misterconsistency-inbox/bod-tools/make_journey.py from journey/SCRIPT.md
   and the clip files; do not edit by hand. Narration: Microsoft neural voice Ryan (en-GB). Music: Kevin MacLeod (incompetech.com),
   Creative Commons: By Attribution 4.0, loudness-matched and re-encoded at 96 kbps. */
window.BOD_JOURNEY = {
 "voice": "Ryan (en-GB), Microsoft neural voice",
 "rooms": [
  {
   "id": "thebes",
   "title": "Thebes, the land of the living",
   "clip": "journey/01-thebes.mp3",
   "dur": 44.83,
   "act": "lament",
   "lines": [
    "Welcome to the world of the Papyrus of Ani: one roll of papyrus, raised in three dimensions, with nothing added that is not labelled.",
    "We begin in Thebes, about 1250 BC, on the only day of the living the roll shows: Ani's burial.",
    "His mummy rides in a shrine on a sledge drawn by oxen, west toward the cliffs.",
    "Eight mourners follow.",
    "A priest in a panther skin burns incense, and Tutu, his wife, kneels and laments.",
    "Ani was a royal scribe and overseer of granaries, yet no house, no temple, no granary is drawn, because the papyrus never describes a building of the living.",
    "When you are ready, walk west with the procession."
   ]
  },
  {
   "id": "west",
   "title": "The Western horizon (Manu)",
   "clip": "journey/02-west.mp3",
   "dur": 36.22,
   "act": "lament",
   "lines": [
    "The Western horizon: the mountain the text calls Manu.",
    "Ra sets here, and the land of Manu receives him; here the dead go in.",
    "Out of the funeral mountain steps Hathor as a cow, wearing the menat, and at the mountain's foot stand a tomb door, flowering plants, and a small shrine where Seker-Osiris, lord of the hidden place, holds his crook and flail.",
    "The cliff is sixty cubits high.",
    "That number is ours: the text gives the mountain a name, not a height.",
    "Through this notch the sun goes down every evening, and through it we follow."
   ]
  },
  {
   "id": "tomb",
   "title": "The tomb in the Western cliffs",
   "clip": "journey/03-tomb.mp3",
   "dur": 44.38,
   "act": "temple",
   "lines": [
    "Ani's tomb: the one room the papyrus draws as a plan, fifteen compartments laid flat on the sheet, which we folded up into a floor and four walls.",
    "At the centre, under a canopy, the bier, and Anubis with his hands over the body.",
    "Isis kneels at the foot, Nephthys at the head, a flame behind each.",
    "The four sons of Horus hold the corners, and two human-headed birds, Ani's soul, perch on pylons: one faces the setting sun, the other the rising.",
    "Every figure here speaks a line of the text.",
    "The room's size, twelve cubits by eight, is our guess.",
    "Outside the door a priest performs the Opening of the Mouth on Ani's statue."
   ]
  },
  {
   "id": "rosetau",
   "title": "Rosetau, the passages",
   "clip": "journey/04-rosetau.mp3",
   "dur": 33.17,
   "act": "temple",
   "lines": [
    "Rosetau, the passages.",
    "The text calls it the northern door of the tomb, and the underworld south of Naarut-f.",
    "\"I have opened the way in Rosetau,\" Ani says.",
    "\"I have made a path for him in the great valley.\" What the passages look like, nobody says: the roll speaks only of \"the door of concealed things\".",
    "So we built one straight stair, a hundred and forty cubits long and as deep, and left it unlit, simply so that the descent reads on the screen.",
    "Down we go."
   ]
  },
  {
   "id": "sycamore",
   "title": "The sycamore of Nut",
   "clip": "journey/05-sycamore.mp3",
   "dur": 33.24,
   "act": "temple",
   "lines": [
    "The first relief after the dark: a pool, and a sycamore.",
    "In its branches the goddess Nut pours water into Ani's hands.",
    "\"Hail, sycamore tree of the goddess Nut,\" the spell runs.",
    "\"Grant thou to me of the water and the air which are in thee.\" Date palms heavy with fruit line the bank, where Ani and Tutu drink.",
    "Where this pool lies on the road, the text never says.",
    "We put it here, just inside the Duat and before the gates, because a traveller would want it here."
   ]
  },
  {
   "id": "duat",
   "title": "The Duat as a whole",
   "clip": "journey/06-duat.mp3",
   "dur": 46.49,
   "act": "rest",
   "lines": [
    "The Duat, the hidden land, seen whole.",
    "Ani describes it himself, to Atum: \"What manner of land is this into which I have come?",
    "It hath not water, it hath not air; it is deep, unfathomable, it is black as the blackest night.\" No acacia grows here, no herb, no grass.",
    "So the model is dark, except where the text puts light: the flames at the gates, the boat of Ra, the Field.",
    "Laying the places along the sun's path, in at the west and out at the east, is our reading; the papyrus gives a sequence of spells, not a map.",
    "The land of the living above is a glass slab, so that you can see down.",
    "About five thousand cubits across: ours again."
   ]
  },
  {
   "id": "arits",
   "title": "The Seven Arits",
   "clip": "journey/07-arits.mp3",
   "dur": 43.22,
   "act": "rest",
   "lines": [
    "The Seven Arits: seven gates in a great valley, each held by three seated guardians, a doorkeeper, a watcher and a herald.",
    "The papyrus names all twenty-one.",
    "At the first gate sit a hare, a serpent and a crocodile; two hold knives, one an ear of corn.",
    "\"Let me not be driven hence,\" Ani says, \"nor from the wall of burning coals,\" so a low wall of embers glows beside the first gate.",
    "The gates themselves, fourteen cubits high and sixty apart, are our invention: the text gives names, never measurements.",
    "Under each of Ani's names you will find the matching gate from another roll, the Papyrus of Nu, as a witness."
   ]
  },
  {
   "id": "pylons",
   "title": "The Ten Pylons of the House of Osiris",
   "clip": "journey/08-pylons.mp3",
   "dur": 43.13,
   "act": "rest",
   "lines": [
    "The Ten Pylons of the House of Osiris.",
    "Each pylon is a goddess with a terrible name.",
    "The first: \"the lady of terrors, with lofty walls, the sovereign lady, the mistress of destruction.\" The sixth cannot be measured: \"man knoweth neither her breadth nor her height; there is a serpent thereover whose size is not known,\" so her towers run up into the dark.",
    "The eighth is \"the blazing fire, the flame whereof cannot be quenched\".",
    "The ninth: \"her girth is three hundred and fifty measures, and she is clothed with mother-of-emerald,\" so we drew her round, and green.",
    "The eleven translucent pylons behind them come from other rolls: witnesses, not Ani."
   ]
  },
  {
   "id": "cities",
   "title": "The holy cities: the councils",
   "clip": "journey/09-cities.mp3",
   "dur": 38.26,
   "act": "rest",
   "lines": [
    "The councils.",
    "Spell 18 asks Thoth to vindicate Ani before ten tribunals: of Heliopolis, of Busiris, of Letopolis, of Pe and Dep, of Abydos, of Rosetau, and the rest.",
    "They are courts in named cities, not stations on a road; the model seats them here, on the last approach to the Hall, and says so.",
    "Two priests, with the side-lock and the leopard skin, lead Ani and Tutu before the seated gods.",
    "The cities themselves are not drawn.",
    "They were real Egyptian towns, and the Book of the Dead never describes one."
   ]
  },
  {
   "id": "hall",
   "title": "The Hall of Two Truths",
   "clip": "journey/10-hall.mp3",
   "dur": 44.06,
   "act": "air",
   "lines": [
    "The Hall of Two Truths: the judgement.",
    "The papyrus draws it: forty-two gods seated in a row down the middle, a door at each end, and a roof crowned with cobras and the feathers of Maat.",
    "At the entrance stands the balance.",
    "Anubis tests the tongue of the scale, Thoth records, Ani's heart is weighed against the feather of Maat, and Ammit, the devourer, waits.",
    "Before the forty-two, Ani denies forty-two sins: \"I have not stolen.",
    "I have not been an eavesdropper.",
    "I have not defiled the wife of any man.\" The hall is a hundred and fifty cubits long, by our arithmetic: forty-two seats at three cubits each."
   ]
  },
  {
   "id": "throne",
   "title": "The throne of Osiris",
   "clip": "journey/11-throne.mp3",
   "dur": 41.57,
   "act": "rites",
   "lines": [
    "The throne of Osiris.",
    "He sits in his shrine, bearded, in the white crown; Isis and Nephthys stand behind him; before him, on a lotus, the four sons of Horus.",
    "Horus leads the justified Ani in, and Ani kneels with his offerings and speaks.",
    "In the Papyrus of Nu the door asks a riddle: who is he whose heaven is of fire, whose walls are living cobras, and the floor of whose house is a stream of water?",
    "It is Osiris.",
    "We did not rebuild the room from a riddle.",
    "The shrine keeps Ani's hawk-headed roof, there is no water underfoot, and the room, forty-four cubits by forty, is ours."
   ]
  },
  {
   "id": "lake",
   "title": "The Lake of Fire",
   "clip": "journey/12-lake.mp3",
   "dur": 26.62,
   "act": "rites",
   "lines": [
    "The Lake of Fire: a square of flame, and at each corner a dog-headed ape, seated.",
    "The papyrus draws it and gives it no text of its own, so we know its shape and nothing more; forty cubits a side is our number.",
    "The spells beside it ask for water to drink, and not to be burned, and not to be scalded.",
    "Elsewhere the roll speaks of a double Lake of Fire.",
    "We show one, and say so."
   ]
  },
  {
   "id": "fields",
   "title": "Sekhet-hetepet, the Field of Reeds",
   "clip": "journey/13-fields.mp3",
   "dur": 46.92,
   "act": "harp",
   "lines": [
    "Sekhet-hetepet, the Field of Reeds: paradise as an ideal Egypt, and the one place the papyrus measures.",
    "\"The river is one thousand cubits in its length.",
    "Not can be told its width.",
    "Not exist fishes any in it, not serpents any in it.\" The wheat stands three cubits high, and the shining ones who live here are seven cubits tall.",
    "Ani ploughs, reaps, drives the oxen that tread out the corn, and sails a boat with a serpent's head at either end.",
    "\"Let me plough there, reap there, eat there, drink there, even as upon earth.\" South of his islands lies the Field as another roll draws it, the Papyrus of Nebseni, with its nine pools and its boat of eight oars."
   ]
  },
  {
   "id": "sky",
   "title": "The sky of Nut and the stars",
   "clip": "journey/14-sky.mp3",
   "dur": 46.3,
   "act": "harp",
   "lines": [
    "The sky of Nut.",
    "The blessed ride here in the boat of the sun, or become stars.",
    "\"Ra rises and shines upon the back of his mother the sky, and the never-resting stars sing.\" In an open hall on the eastern bank lie the seven cows before their tables of offerings, with a bull and the four rudders of heaven, one for each quarter.",
    "A ladder climbs from the bank into the sky: the way of the soul.",
    "Along the bank perch Ani's transformations, eleven of them: a swallow, a golden hawk with a back seven cubits wide, a serpent, a crocodile, a heron, a lotus, light itself.",
    "The goddess we did not draw.",
    "The text speaks of her back and her hands; the papyrus never pictures her."
   ]
  },
  {
   "id": "boat",
   "title": "The night boat of Ra",
   "clip": "journey/15-boat.mp3",
   "dur": 38.42,
   "act": "vale",
   "lines": [
    "The night boat of Ra.",
    "Ra, hawk-headed, sits in a shrine amidships; Horus holds the rudder, with Thoth and Maat beside him; and Ani, by his own words, grasps the bows of the evening boat and the stern of the boat of morning.",
    "The boat is seven cubits long and painted green, because a rubric prescribes a model boat for the rite, and that is the only boat length the papyrus gives.",
    "Ahead in the water waits the serpent Apep; on the bank, the Cat of the Sun, who kills him.",
    "The river itself is our trench along the south of the Duat.",
    "Ani speaks of the crossing, but never describes the water."
   ]
  },
  {
   "id": "east",
   "title": "The Eastern horizon (Bakhu)",
   "clip": "journey/16-east.mp3",
   "dur": 36.79,
   "act": "vale",
   "lines": [
    "The Eastern horizon, Bakhu: where Ra is reborn each morning, and where the justified come forth by day.",
    "A pair of arms lifts the sun's disk from the djed pillar; six baboons adore it; Isis and Nephthys kneel.",
    "The gate is the two leaves of the door through which Tmu passes into the eastern sky.",
    "Ani and Tutu stand in the morning boat and adore Khepera, the rising sun.",
    "This is the name of the whole book: the Spells of Coming Forth by Day.",
    "The eastern cliff mirrors the western, sixty cubits high: symmetry, not text."
   ]
  },
  {
   "id": "aats",
   "title": "The fourteen Aats of the Papyrus of Nu",
   "clip": "journey/17-aats.mp3",
   "dur": 47.54,
   "act": "temple",
   "lines": [
    "One last room, and it is not Ani's.",
    "Along the north of the Duat lie the fourteen Aats of the Papyrus of Nu, another roll in the British Museum: walled domains, each with a speech, and a paint instruction, green or yellow.",
    "In the second, Sekhet-Aarru, the walls are of iron and the wheat stands five cubits, or seven, depending on your translator.",
    "In the fourth, a serpent seventy cubits long lives by slaughtering the dead.",
    "In the ninth no one enters but the god who dwells in his egg.",
    "Nu gives no positions, so the band is ours.",
    "Where Ani is silent, the ledger lets another witness speak, and marks it.",
    "That is the whole world.",
    "Thank you for walking it."
   ]
  }
 ],
 "music": {
  "lament": {
   "file": "journey/music/lamentation.mp3",
   "title": "Lamentation",
   "dur": 197.64
  },
  "temple": {
   "file": "journey/music/temple-of-the-manes.mp3",
   "title": "Temple of the Manes",
   "dur": 155.64
  },
  "rest": {
   "file": "journey/music/ossuary-5-rest.mp3",
   "title": "Ossuary 5 - Rest",
   "dur": 235.81
  },
  "air": {
   "file": "journey/music/ossuary-6-air.mp3",
   "title": "Ossuary 6 - Air",
   "dur": 250.1
  },
  "rites": {
   "file": "journey/music/rites.mp3",
   "title": "Rites",
   "dur": 126.96
  },
  "harp": {
   "file": "journey/music/enchanted-journey.mp3",
   "title": "Enchanted Journey",
   "dur": 269.58
  },
  "vale": {
   "file": "journey/music/ascending-the-vale.mp3",
   "title": "Ascending the Vale",
   "dur": 247.67
  }
 }
};
